In [1]:
import numpy as np
import pandas as pd


In [2]:
from sklearn.datasets import load_iris

In [3]:
dataset=load_iris()

In [5]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [14]:
dataset.target_names
## this dataset has three classes below

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [15]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [16]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

## Independent and Dependent features

In [17]:
x=df
y=dataset.target

In [21]:
x.head(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2

In [22]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## train test split

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

## Logistic regression multiclass classification

In [25]:
from sklearn.linear_model import LogisticRegression

In [36]:
m_logistic=LogisticRegression(multi_class='ovr',solver='lbfgs')## we will take solver='lbfgs for multiclass'

In [37]:
m_logistic.fit(x_train,y_train)

LogisticRegression(multi_class='ovr')

In [38]:
y_pred=m_logistic.predict(x_test)

In [39]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2, 1, 0,
       0])

In [40]:
m_logistic.predict_proba(x_test)

array([[6.44486670e-03, 7.10028239e-01, 2.83526894e-01],
       [9.40640428e-01, 5.93466747e-02, 1.28968648e-05],
       [4.27583523e-06, 3.72240473e-01, 6.27755251e-01],
       [1.05026861e-02, 6.27469769e-01, 3.62027545e-01],
       [3.19065156e-03, 6.04506551e-01, 3.92302797e-01],
       [8.90030777e-01, 1.09958193e-01, 1.10294502e-05],
       [1.44596655e-01, 8.07960377e-01, 4.74429686e-02],
       [7.02232333e-04, 1.75065698e-01, 8.24232069e-01],
       [3.30532731e-03, 7.37327882e-01, 2.59366790e-01],
       [4.96354657e-02, 8.86278752e-01, 6.40857822e-02],
       [1.25794565e-03, 2.11563095e-01, 7.87178960e-01],
       [7.52945666e-01, 2.47048946e-01, 5.38744004e-06],
       [9.04900272e-01, 9.50956416e-02, 4.08626950e-06],
       [7.75656673e-01, 2.24336526e-01, 6.80126837e-06],
       [9.40919350e-01, 5.90718108e-02, 8.83895035e-06],
       [9.09227484e-03, 3.79824758e-01, 6.11082967e-01],
       [1.44334180e-04, 2.48363286e-01, 7.51492380e-01],
       [3.99529351e-02, 9.11896

In [41]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [42]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[19  0  0]
 [ 0 11  2]
 [ 0  0 13]]
0.9555555555555556
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.85      0.92        13
           2       0.87      1.00      0.93        13

    accuracy                           0.96        45
   macro avg       0.96      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45



In [61]:
##  one thing to remember is that unlike 2*2 matrix top is predicted and left is true

In [43]:
## one versus rest just replace 'multinomial' with 'ovr'

In [52]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.85      0.92        13
           2       0.87      1.00      0.93        13

    accuracy                           0.96        45
   macro avg       0.96      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45

