## Naive Baye's 

In [1]:
import numpy as np
import pandas as pd


In [2]:
from sklearn.datasets import load_iris

In [11]:
x,y=load_iris(return_X_y=True)

In [3]:
from sklearn.model_selection import train_test_split

In [14]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [16]:
from sklearn.naive_bayes import GaussianNB

In [18]:
gnb=GaussianNB()

In [19]:
gnb.fit(x_train,y_train)

GaussianNB()

In [20]:
y_pred=gnb.predict(x_test)

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [22]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [23]:
import seaborn as sns

In [25]:
tip=sns.load_dataset('tips')

In [26]:
tip.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [27]:
from sklearn.preprocessing import OneHotEncoder

In [28]:
ohe=OneHotEncoder()

In [36]:
encoded=ohe.fit_transform(tip[['sex','smoker','day']])

In [37]:
encoded_data=encoded.toarray()

In [39]:
df_encoded=pd.DataFrame(encoded_data,columns=ohe.get_feature_names_out())

In [42]:
df_final=pd.concat([tip,df_encoded],axis=1)

In [43]:
df_final

total_bill   tip     sex smoker   day    time  size  sex_Female  \
0         16.99  1.01  Female     No   Sun  Dinner     2         1.0   
1         10.34  1.66    Male     No   Sun  Dinner     3         0.0   
2         21.01  3.50    Male     No   Sun  Dinner     3         0.0   
3         23.68  3.31    Male     No   Sun  Dinner     2         0.0   
4         24.59  3.61  Female     No   Sun  Dinner     4         1.0   
..          ...   ...     ...    ...   ...     ...   ...         ...   
239       29.03  5.92    Male     No   Sat  Dinner     3         0.0   
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1.0   
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0.0   
242       17.82  1.75    Male     No   Sat  Dinner     2         0.0   
243       18.78  3.00  Female     No  Thur  Dinner     2         1.0   

     sex_Male  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  day_Thur  
0         0.0        1.0         0.0      0.0      0.0      1.0       0.0  
1         1.0        1.0         0.0      0.0      0.0      1.0       0.0  
2         1.0        1.0         0.0      0.0      0.0      1.0       0.0  
3         1.0        1.0         0.0      0.0      0.0      1.0       0.0  
4         0.0        1.0         0.0      0.0      0.0      1.0       0.0  
..        ...        ...         ...      ...      ...      ...       ...  
239       1.0        1.0         0.0      0.0      1.0      0.0       0.0  
240       0.0        0.0         1.0      0.0      1.0      0.0       0.0  
241       1.0        0.0         1.0      0.0      1.0      0.0       0.0  
242       1.0        1.0         0.0      0.0      1.0      0.0       0.0  
243       0.0        1.0         0.0      0.0      0.0      0.0       1.0  

[244 rows x 15 columns]

In [45]:
df_final=df_final.drop(columns=['sex','smoker','day'])

In [46]:
df_final.head()

total_bill   tip    time  size  sex_Female  sex_Male  smoker_No  \
0       16.99  1.01  Dinner     2         1.0       0.0        1.0   
1       10.34  1.66  Dinner     3         0.0       1.0        1.0   
2       21.01  3.50  Dinner     3         0.0       1.0        1.0   
3       23.68  3.31  Dinner     2         0.0       1.0        1.0   
4       24.59  3.61  Dinner     4         1.0       0.0        1.0   

   smoker_Yes  day_Fri  day_Sat  day_Sun  day_Thur  
0         0.0      0.0      0.0      1.0       0.0  
1         0.0      0.0      0.0      1.0       0.0  
2         0.0      0.0      0.0      1.0       0.0  
3         0.0      0.0      0.0      1.0       0.0  
4         0.0      0.0      0.0      1.0       0.0

## we have to find time based on other features

In [47]:
x=df_final.drop(['time'],axis=1)

In [48]:
x

total_bill   tip  size  sex_Female  sex_Male  smoker_No  smoker_Yes  \
0         16.99  1.01     2         1.0       0.0        1.0         0.0   
1         10.34  1.66     3         0.0       1.0        1.0         0.0   
2         21.01  3.50     3         0.0       1.0        1.0         0.0   
3         23.68  3.31     2         0.0       1.0        1.0         0.0   
4         24.59  3.61     4         1.0       0.0        1.0         0.0   
..          ...   ...   ...         ...       ...        ...         ...   
239       29.03  5.92     3         0.0       1.0        1.0         0.0   
240       27.18  2.00     2         1.0       0.0        0.0         1.0   
241       22.67  2.00     2         0.0       1.0        0.0         1.0   
242       17.82  1.75     2         0.0       1.0        1.0         0.0   
243       18.78  3.00     2         1.0       0.0        1.0         0.0   

     day_Fri  day_Sat  day_Sun  day_Thur  
0        0.0      0.0      1.0       0.0  
1        0.0      0.0      1.0       0.0  
2        0.0      0.0      1.0       0.0  
3        0.0      0.0      1.0       0.0  
4        0.0      0.0      1.0       0.0  
..       ...      ...      ...       ...  
239      0.0      1.0      0.0       0.0  
240      0.0      1.0      0.0       0.0  
241      0.0      1.0      0.0       0.0  
242      0.0      1.0      0.0       0.0  
243      0.0      0.0      0.0       1.0  

[244 rows x 11 columns]

In [49]:
y=df_final['time']

In [50]:
y

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...  
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [52]:
from sklearn.naive_bayes import GaussianNB

In [53]:
gnb=GaussianNB()

In [54]:
gnb.fit(x_train,y_train)

GaussianNB()

In [55]:
y_pred=gnb.predict(x_test)

In [56]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[55  1]
 [ 5 13]]
0.918918918918919
              precision    recall  f1-score   support

      Dinner       0.92      0.98      0.95        56
       Lunch       0.93      0.72      0.81        18

    accuracy                           0.92        74
   macro avg       0.92      0.85      0.88        74
weighted avg       0.92      0.92      0.92        74



In [57]:
y_pred

array(['Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Lunch',
       'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Lunch', 'Lunch',
       'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner',
       'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Lunch',
       'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Dinner',
       'Dinner', 'Dinner', 'Lunch', 'Dinner', 'Dinner', 'Dinner',
       'Dinner', 'Dinner', 'Dinner', 'Dinner'], dtype='<U6')