In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [3]:
arr=np.array(l)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4])

In [7]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [8]:
b=np.matrix(l)

In [9]:
b

matrix([[1, 2, 3, 4]])

In [10]:
##matrix is a subset of array so it will not change it
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [11]:
a=np.array(l)

In [12]:
a

array([1, 2, 3, 4])

In [13]:
##this is solo copy
d=a

In [14]:
d

array([1, 2, 3, 4])

In [15]:
d[0]

1

In [16]:
d[0]=100

In [17]:
d

array([100,   2,   3,   4])

In [18]:
a

array([100,   2,   3,   4])

In [19]:
a

array([100,   2,   3,   4])

In [20]:
##this is deep copy
x=np.copy(a)

In [21]:
x

array([100,   2,   3,   4])

In [22]:
x[0]=500

In [23]:
x

array([500,   2,   3,   4])

In [24]:
a

array([100,   2,   3,   4])

In [25]:
y=np.array([1,2,3,4,5,6])

In [26]:
y

array([1, 2, 3, 4, 5, 6])

In [27]:
y=y.reshape(3,2)

In [28]:
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
y.nbytes

24

In [30]:
y.ndim

2

In [31]:
y.shape

(3, 2)

In [32]:
np.ones((3,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [34]:
np.fromfunction(lambda i,j:i*j,(3,3),dtype='int32')

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [35]:
np.fromfunction(lambda i,j:i!=j,(3,3),dtype='int32')

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [36]:
iterable=(i*i for i in range(5))

In [37]:
for i in iterable:
    print(i)

0
1
4
9
16


In [38]:
np.fromiter(iterable,dtype='int32')

array([], dtype=int32)

In [39]:
np.fromstring('23 34 34',sep=' ',dtype='int32')

array([23, 34, 34])

In [40]:
np.fromstring('2,4,34,24,2,45,56',sep=',')

array([ 2.,  4., 34., 24.,  2., 45., 56.])

In [41]:
##range function in numpy
np.arange(0.3,4.6)

array([0.3, 1.3, 2.3, 3.3, 4.3])

In [42]:
np.arange(0.5,20,2)

array([ 0.5,  2.5,  4.5,  6.5,  8.5, 10.5, 12.5, 14.5, 16.5, 18.5])

In [43]:
##iinspace will divide the range in equal parts in this case 8 equal parts from 2 to 10
np.linspace(2,10,8)

array([ 2.        ,  3.14285714,  4.28571429,  5.42857143,  6.57142857,
        7.71428571,  8.85714286, 10.        ])

In [47]:
np.zeros((3,4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [50]:
one=np.ones((3,3))

In [51]:
one*2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [52]:
one+2

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [60]:
np.empty((5,3),dtype='int32')

array([[      0,       0,       0],
       [      0,       0,       0],
       [      0,       0,       0],
       [      0,    2384,       0],
       [      0, 7602273,       0]])

In [64]:
##identity matrix
np.eye(5,dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [71]:
##it is like linspace it also divide the range in this case 10 equal parts and then find the log
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [90]:
##it gives the data from the standard normal distribution that is whose mean is zero and standard 
##deviation is 1
np.random.randn(4,2)

array([[-1.2745396 ,  0.47355721],
       [ 0.68424252,  0.50794262],
       [ 0.25004784,  0.27596195],
       [-0.51015417, -0.72409282]])

In [91]:
##it generates the random data
np.random.rand(3,3)

array([[0.91757159, 0.67632197, 0.67161999],
       [0.73651483, 0.62433877, 0.07855705],
       [0.59903394, 0.72127079, 0.154953  ]])

In [98]:
dt=np.random.randint(-10,20,(3,4))

In [99]:
dt

array([[10, -1, 18, -1],
       [ 6,  1,  1, -1],
       [13,  2, 13, -9]])

In [100]:
import pandas as pd

In [101]:
pd.DataFrame(dt)

0  1   2  3
0  10 -1  18 -1
1   6  1   1 -1
2  13  2  13 -9

In [102]:
dt

array([[10, -1, 18, -1],
       [ 6,  1,  1, -1],
       [13,  2, 13, -9]])

In [113]:
##by default it will take rows multiple of 12 according to column
dt.reshape(-2,3)

array([[10, -1, 18],
       [-1,  6,  1],
       [ 1, -1, 13],
       [ 2, 13, -9]])

In [115]:
##by default it will take column
dt.reshape(3,-123)

array([[10, -1, 18, -1],
       [ 6,  1,  1, -1],
       [13,  2, 13, -9]])

In [118]:
arr3=np.random.randint(1,100,(5,5))

In [119]:
arr3

array([[ 3, 24, 87, 99, 55],
       [ 2, 90, 26, 36, 63],
       [94,  7, 94, 36, 62],
       [ 1, 57, 32, 88, 44],
       [69, 83, 44, 99, 99]])

In [121]:
##finding the number which is greater than 50
arr3[arr3>50]

array([87, 99, 55, 90, 63, 94, 94, 62, 57, 88, 69, 83, 99, 99])

In [122]:
arr3

array([[ 3, 24, 87, 99, 55],
       [ 2, 90, 26, 36, 63],
       [94,  7, 94, 36, 62],
       [ 1, 57, 32, 88, 44],
       [69, 83, 44, 99, 99]])

In [126]:
arr3[2:4,[1,3]]

array([[ 7, 36],
       [57, 88]])

In [127]:
arr3[0][0]

3

In [128]:
arr3[0,0]

3

In [129]:
arr3[2][3]

36

In [132]:
arr3[2,3]

36

In [133]:
a1=np.random.randint(1,4,(3,3))
a2=np.random.randint(1,4,(3,3))

In [134]:
a1

array([[2, 2, 3],
       [2, 3, 3],
       [2, 1, 2]])

In [135]:
a2

array([[3, 1, 2],
       [3, 3, 3],
       [2, 1, 3]])

In [137]:
##this is not a matrix multiplication but it is a multiplication index wise
a1*a2

array([[6, 2, 6],
       [6, 9, 9],
       [4, 1, 6]])

In [145]:
##this is matrix multiplication
np.matmul(a1,a2)

array([[18, 11, 19],
       [21, 14, 22],
       [13,  7, 13]])

In [146]:
##this is matrix multiplication
a1@a2

array([[18, 11, 19],
       [21, 14, 22],
       [13,  7, 13]])

In [147]:
a1

array([[2, 2, 3],
       [2, 3, 3],
       [2, 1, 2]])

In [148]:
np.linalg.det(a1)

-2.0

In [152]:
##broadcasting in numpy
ar=np.zeros((3,3))

In [157]:
row=np.array([1,2,3])

In [158]:
ar+row

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [159]:
##we are adding row by row this is row wise broadcasting

In [161]:
##for broadcasting column wise
row2=row.reshape(3,1)

In [162]:
ar+row2

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [163]:
row2

array([[1],
       [2],
       [3]])

In [165]:
np.sin(row2)

array([[0.84147098],
       [0.90929743],
       [0.14112001]])

In [166]:
np.sqrt(row2)

array([[1.        ],
       [1.41421356],
       [1.73205081]])

In [168]:
td=np.array([[1,2,3],[4,5,6]])

In [169]:
td

array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
td.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [176]:
j=np.array([1,2,3])

In [177]:
j.T

array([1, 2, 3])

In [178]:
k=np.array([[1,2,3]])

In [180]:
k

array([[1, 2, 3]])

In [185]:
##transpose of matrix
k.T

array([[1],
       [2],
       [3]])

In [181]:
td

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
##converting the matrix into single array
td.flatten()

array([1, 2, 3, 4, 5, 6])

In [187]:
##transpose of matrix
td.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [188]:
##to convert from 1-d to 2-d
arr5=np.array([1,2,3,4])

In [189]:
arr5

array([1, 2, 3, 4])

In [190]:
arr5.ndim

1

In [191]:
np.expand_dims(arr5,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [192]:
np.expand_dims(arr5,axis=0)

array([[1, 2, 3, 4]])

In [204]:
##here axis=1 means row wise
td.min(axis=1)

array([1, 4])

In [205]:
##here axis=0 means column wise
np.min(td,axis=0)

array([1, 2, 3])

In [206]:
td

array([[1, 2, 3],
       [4, 5, 6]])

In [208]:
np.expand_dims(td,axis=1)

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [209]:
arr6=np.array([[1],[2],[3]])

In [210]:
arr6

array([[1],
       [2],
       [3]])

In [211]:
np.squeeze(arr6)

array([1, 2, 3])

In [212]:
arr7=np.array([1,2,1,3])

In [225]:
np.repeat(arr7,3)

array([1, 1, 1, 2, 2, 2, 1, 1, 1, 3, 3, 3])

In [226]:
##shifting the positions of elements in right
arr8=np.array([4,5,6,7,8])

In [227]:
arr8

array([4, 5, 6, 7, 8])

In [228]:
np.roll(arr8,2)

array([7, 8, 4, 5, 6])

In [229]:
np.diag(arr8)

array([[4, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 8]])

In [230]:
td

array([[1, 2, 3],
       [4, 5, 6]])

In [231]:
~td

array([[-2, -3, -4],
       [-5, -6, -7]])

In [236]:
##string function in numpy
np.fromstring('234 32 56',sep=' ')

array([234.,  32.,  56.])

In [237]:
arr9=np.array(['jai','yadav'])

In [238]:
arr9

array(['jai', 'yadav'], dtype='<U5')

In [239]:
np.char.upper(arr9)

array(['JAI', 'YADAV'], dtype='<U5')

In [240]:
np.char.title(arr9)

array(['Jai', 'Yadav'], dtype='<U5')

In [242]:
##mathematical functions in numpy

In [243]:
td

array([[1, 2, 3],
       [4, 5, 6]])

In [244]:
np.sin(td)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [245]:
np.log2(td)

array([[0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 ]])

In [246]:
np.log10(td)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [249]:
np.exp(td)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [250]:
np.sqrt(td)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [252]:
np.power(td,3)

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)

In [253]:
np.min(td)

1

In [254]:
np.mean(td)

3.5

In [255]:
td

array([[1, 2, 3],
       [4, 5, 6]])

In [257]:
np.min(td,axis=1)

array([1, 4])

In [262]:
tt=np.random.randint(1,10,(3,3))

In [263]:
np.min(tt,axis=0)

array([2, 2, 1])

In [264]:
tt

array([[9, 7, 1],
       [2, 6, 2],
       [3, 2, 2]])

In [265]:
np.min(tt,axis=1)

array([1, 2, 2])

In [266]:
## search,sort and counting function
np.sort(tt)

array([[1, 7, 9],
       [2, 2, 6],
       [2, 2, 3]])

In [268]:
arr10=np.array([1,23,5,34,32,56,22])

In [269]:
arr10

array([ 1, 23,  5, 34, 32, 56, 22])

In [281]:
##it will tell after what index the particular value will fit
np.searchsorted(arr10,30)

3

In [282]:
np.sort(arr10)

array([ 1,  5, 22, 23, 32, 34, 56])

In [283]:
arr11=np.array([1,2,0,0,5,4,0,7,0])

In [286]:
np.count_nonzero(arr11)

5

In [293]:
##it will give the index
np.where(arr10>30)

(array([3, 4, 5], dtype=int64),)

In [301]:
##getting data from array
np.extract(arr10>10,arr10)

array([23, 34, 32, 56, 22])

In [312]:
##view 
##view is also solo copy
a=np.array([1,2,3,4])

In [313]:
b=a.view()

In [314]:
b

array([1, 2, 3, 4])

In [315]:
b[0]=5

In [316]:
a

array([5, 2, 3, 4])

In [317]:
##matrix
import numpy.matlib as nm

In [318]:
nm.zeros((3,4))

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [319]:
nm.ones((4,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [321]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [322]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [323]:
##matrix is a subset of array

In [324]:
a1

array([[2, 2, 3],
       [2, 3, 3],
       [2, 1, 2]])

In [325]:
a2

array([[3, 1, 2],
       [3, 3, 3],
       [2, 1, 3]])

In [330]:
##matrix multiplication
np.dot(a1,a2)

array([[18, 11, 19],
       [21, 14, 22],
       [13,  7, 13]])

In [331]:
a1@a2

array([[18, 11, 19],
       [21, 14, 22],
       [13,  7, 13]])

In [332]:
np.matmul(a1,a2)

array([[18, 11, 19],
       [21, 14, 22],
       [13,  7, 13]])

In [333]:
p=np.array([[2,3],[4,-3]])

In [334]:
q=np.array([4,2])

In [337]:
np.linalg.solve(p,q)

array([1.        , 0.66666667])