In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [17]:
from sklearn.decomposition import PCA


In [19]:
from sklearn.datasets import load_iris

In [21]:
iris=load_iris()

In [47]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [32]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [33]:
x=iris.data

In [35]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [37]:
y=iris.target

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [41]:
## PCA is a transformation technique
pca=PCA(n_components=3) ## we want three features out of four

In [42]:
x_train=pca.fit_transform(x_train)

In [43]:
x_train

array([[-3.19809613e-01, -6.05348170e-01, -3.26338094e-01],
       [ 1.32748645e+00, -1.10665523e-01, -1.69354196e-01],
       [ 1.79450873e+00,  6.14314403e-02,  1.48612379e-01],
       [ 7.92127577e-01,  3.77984923e-01, -3.07968171e-01],
       [ 2.82233703e+00,  7.62500823e-01,  4.33892944e-01],
       [ 2.57313290e-01, -2.43498191e-01,  6.44412424e-02],
       [ 3.29429267e+00,  5.44686773e-01, -3.52148810e-01],
       [ 5.41525286e-01, -3.17525946e-01,  3.09546404e-01],
       [-2.78933480e+00,  4.41451862e-01, -1.32970257e-03],
       [ 3.39404833e+00,  4.59441452e-01, -5.80769348e-01],
       [ 1.14921657e-01, -2.69437408e-01, -2.86655671e-01],
       [-2.74586793e+00,  4.36734540e-01, -1.18396593e-01],
       [-2.87649191e+00,  3.84090975e-01,  1.04412332e-01],
       [-2.30949060e+00,  5.37738148e-01,  3.22150116e-01],
       [-6.51513641e-01, -1.18461155e+00, -3.05080700e-01],
       [ 1.26934877e+00, -1.73732914e-01, -7.48883663e-02],
       [-2.46688042e+00,  7.31965446e-02

In [44]:
pca.components_

array([[ 0.37167593, -0.06299273,  0.85531578,  0.35542065],
       [ 0.66585782,  0.71303104, -0.19438974, -0.10214078],
       [-0.55627639,  0.61439252,  0.05561896,  0.55676291]])

In [45]:
pca.explained_variance_ratio_

array([0.9191876 , 0.05549301, 0.02010131])